- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io
    become : yes
    become_user : rr
    
  - name : Start Docker Service
    command : sudo systemctl start docker
    become : yes
    become_user : rr
    
  - name: Deploy Docker Container
    command: docker run -itd -p 1212:8081 rajeshraji/bank-project:1.3
